JoGroup = JoGroup or {}
local Jo = JoGroup

-------------------------------------------------------------------------------------------------
--  Buffs --
-------------------------------------------------------------------------------------------------
Jo.isHorny = {
	[38564] = "War Horn I",
	[46526] = "War Horn II",
	[46528] = "War Horn III",
	[46530] = "War Horn IV",
	[40224] = "Aggressive Horn I",
	[46532] = "Aggressive Horn II",
	[46535] = "Aggressive Horn III",
	[46538] = "Aggressive Horn IV",
	[40221] = "Sturdy Horn I",
	[46541] = "Sturdy Horn II",
	[46544] = "Sturdy Horn III",
	[46547] = "Sturdy Horn IV",
}

Jo.hasCRShade = {
	[102271] = "Shadow of the Fallen",
}

local FOOD_BUFF_NONE = 0
local FOOD_BUFF_MAX_HEALTH = 1
local FOOD_BUFF_MAX_MAGICKA = 2
local FOOD_BUFF_MAX_STAMINA = 4
local FOOD_BUFF_REGEN_HEALTH = 8
local FOOD_BUFF_REGEN_MAGICKA = 16
local FOOD_BUFF_REGEN_STAMINA = 32
local FOOD_BUFF_SPECIAL_VAMPIRE = 64
local FOOD_BUFF_SPECIAL_FISHING = 128
local FOOD_BUFF_MAX_HEALTH_MAGICKA = FOOD_BUFF_MAX_HEALTH + FOOD_BUFF_MAX_MAGICKA
local FOOD_BUFF_MAX_HEALTH_STAMINA = FOOD_BUFF_MAX_HEALTH + FOOD_BUFF_MAX_STAMINA
local FOOD_BUFF_MAX_MAGICKA_STAMINA = FOOD_BUFF_MAX_MAGICKA + FOOD_BUFF_MAX_STAMINA
local FOOD_BUFF_REGEN_HEALTH_MAGICKA = FOOD_BUFF_REGEN_HEALTH + FOOD_BUFF_REGEN_MAGICKA
local FOOD_BUFF_REGEN_HEALTH_STAMINA = FOOD_BUFF_REGEN_HEALTH + FOOD_BUFF_REGEN_STAMINA
local FOOD_BUFF_REGEN_MAGICKA_STAMINA = FOOD_BUFF_REGEN_MAGICKA + FOOD_BUFF_REGEN_STAMINA
local FOOD_BUFF_MAX_ALL = FOOD_BUFF_MAX_HEALTH + FOOD_BUFF_MAX_MAGICKA + FOOD_BUFF_MAX_STAMINA
local FOOD_BUFF_REGEN_ALL = FOOD_BUFF_REGEN_HEALTH + FOOD_BUFF_REGEN_MAGICKA + FOOD_BUFF_REGEN_STAMINA
local FOOD_BUFF_MAX_HEALTH_REGEN_HEALTH = FOOD_BUFF_MAX_HEALTH + FOOD_BUFF_REGEN_HEALTH
local FOOD_BUFF_MAX_HEALTH_REGEN_MAGICKA = FOOD_BUFF_MAX_HEALTH + FOOD_BUFF_REGEN_MAGICKA
local FOOD_BUFF_MAX_HEALTH_REGEN_STAMINA = FOOD_BUFF_MAX_HEALTH + FOOD_BUFF_REGEN_STAMINA
local FOOD_BUFF_MAX_HEALTH_REGEN_ALL = FOOD_BUFF_MAX_HEALTH + FOOD_BUFF_REGEN_HEALTH + FOOD_BUFF_REGEN_MAGICKA + FOOD_BUFF_REGEN_STAMINA
local FOOD_BUFF_MAX_MAGICKA_REGEN_STAMINA = FOOD_BUFF_MAX_MAGICKA + FOOD_BUFF_REGEN_STAMINA
local FOOD_BUFF_MAX_MAGICKA_REGEN_HEALTH = FOOD_BUFF_MAX_MAGICKA + FOOD_BUFF_REGEN_HEALTH
local FOOD_BUFF_MAX_MAGICKA_REGEN_MAGICKA = FOOD_BUFF_MAX_MAGICKA + FOOD_BUFF_REGEN_MAGICKA
local FOOD_BUFF_MAX_HEALTH_MAGICKA_REGEN_MAGICKA = FOOD_BUFF_MAX_HEALTH + FOOD_BUFF_MAX_MAGICKA + FOOD_BUFF_REGEN_MAGICKA
local FOOD_BUFF_MAX_HEALTH_MAGICKA_SPECIAL_VAMPIRE = FOOD_BUFF_MAX_HEALTH + FOOD_BUFF_MAX_MAGICKA + FOOD_BUFF_SPECIAL_VAMPIRE
local FOOD_BUFF_MAX_STAMINA_REGEN_STAMINA = FOOD_BUFF_MAX_STAMINA + FOOD_BUFF_REGEN_STAMINA
local FOOD_BUFF_MAX_STAMINA_REGEN_HEALTH = FOOD_BUFF_MAX_STAMINA + FOOD_BUFF_REGEN_HEALTH
local FOOD_BUFF_REGEN_MAGICKA_STAMINA_FISHING = FOOD_BUFF_REGEN_MAGICKA + FOOD_BUFF_REGEN_STAMINA + FOOD_BUFF_SPECIAL_FISHING
local FOOD_BUFF_REGEN_STAMINA_MAX_STAMINA_MAX_HEALTH = FOOD_BUFF_REGEN_STAMINA + FOOD_BUFF_MAX_STAMINA + FOOD_BUFF_MAX_HEALTH
local FOOD_BUFF_MAX_STAMINA_REGEN_MAGICKA = FOOD_BUFF_MAX_STAMINA + FOOD_BUFF_REGEN_MAGICKA
local FOOD_BUFF_REGEN_STAMINA_REGEN_MAGICKA_MAX_HEALTH = FOOD_BUFF_REGEN_STAMINA + FOOD_BUFF_REGEN_MAGICKA + FOOD_BUFF_MAX_HEALTH
local FOOD_BUFF_REGEN_HEALTH_MAX_HEALTH_MAX_MAGICKA = FOOD_BUFF_REGEN_HEALTH + FOOD_BUFF_MAX_HEALTH + FOOD_BUFF_MAX_MAGICKA
local FOOD_BUFF_REGEN_HEALTH_REGEN_MAGICKA_MAX_HEALTH_MAX_MAGICKA = FOOD_BUFF_REGEN_MAGICKA + FOOD_BUFF_REGEN_HEALTH + FOOD_BUFF_MAX_HEALTH + FOOD_BUFF_MAX_MAGICKA
local FOOD_BUFF_MAX_HEALTH_MAGICKA_FISHING = FOOD_BUFF_MAX_HEALTH + FOOD_BUFF_MAX_MAGICKA + FOOD_BUFF_SPECIAL_FISHING

Jo.isFoodBuff = {
	[61259] = FOOD_BUFF_MAX_HEALTH,
	[61260] = FOOD_BUFF_MAX_MAGICKA,
	[61261] = FOOD_BUFF_MAX_STAMINA,
	[61322] = FOOD_BUFF_REGEN_HEALTH,
	[61325] = FOOD_BUFF_REGEN_MAGICKA,
	[61328] = FOOD_BUFF_REGEN_STAMINA,
	[61257] = FOOD_BUFF_MAX_HEALTH_MAGICKA,
	[61255] = FOOD_BUFF_MAX_HEALTH_STAMINA,
	[61294] = FOOD_BUFF_MAX_MAGICKA_STAMINA,
	[72816] = FOOD_BUFF_REGEN_HEALTH_MAGICKA,
	[61340] = FOOD_BUFF_REGEN_HEALTH_STAMINA,
	[61345] = FOOD_BUFF_REGEN_MAGICKA_STAMINA,
	[61218] = FOOD_BUFF_MAX_ALL,
	[61350] = FOOD_BUFF_REGEN_ALL,
	[72822] = FOOD_BUFF_MAX_HEALTH_REGEN_HEALTH,
	[72816] = FOOD_BUFF_MAX_HEALTH_REGEN_MAGICKA,
	[72819] = FOOD_BUFF_MAX_HEALTH_REGEN_STAMINA,
	[72824] = FOOD_BUFF_MAX_HEALTH_REGEN_ALL,
	-- crown store
	[68411] = FOOD_BUFF_MAX_ALL,
	[68416] = FOOD_BUFF_REGEN_ALL,
	-- 2h Witches event
	[84681] = FOOD_BUFF_MAX_MAGICKA_STAMINA,
	[84709] = FOOD_BUFF_MAX_MAGICKA_REGEN_STAMINA,
	[84725] = FOOD_BUFF_MAX_MAGICKA_REGEN_HEALTH,
	[84678] = FOOD_BUFF_MAX_MAGICKA,
	[84704] = FOOD_BUFF_REGEN_ALL,
	[84720] = FOOD_BUFF_MAX_MAGICKA_REGEN_MAGICKA,
	[84700] = FOOD_BUFF_REGEN_HEALTH_MAGICKA,
	[84731] = FOOD_BUFF_MAX_HEALTH_MAGICKA_REGEN_MAGICKA,
	[84735] = FOOD_BUFF_MAX_HEALTH_MAGICKA_SPECIAL_VAMPIRE,
	-- new years event
	[86791] = FOOD_BUFF_REGEN_STAMINA,
	[86787] = FOOD_BUFF_MAX_STAMINA,
	[86673] = FOOD_BUFF_MAX_STAMINA_REGEN_STAMINA,
	[86749] = FOOD_BUFF_MAX_MAGICKA_REGEN_STAMINA,
	[86677] = FOOD_BUFF_MAX_STAMINA_REGEN_HEALTH,
	[86789] = FOOD_BUFF_MAX_HEALTH,
	[84678] = FOOD_BUFF_MAX_MAGICKA,
	[86559] = FOOD_BUFF_REGEN_MAGICKA_STAMINA_FISHING,
	[86746] = FOOD_BUFF_REGEN_HEALTH_MAGICKA,	
	-- jesters festival
	[84678] = FOOD_BUFF_MAX_MAGICKA,
	[89957] = FOOD_BUFF_REGEN_STAMINA_MAX_STAMINA_MAX_HEALTH,
	[89955] = FOOD_BUFF_MAX_STAMINA_REGEN_MAGICKA,
	[89971] = FOOD_BUFF_REGEN_STAMINA_REGEN_MAGICKA_MAX_HEALTH,
	-- pvp foods
	[72956] = FOOD_BUFF_MAX_HEALTH_STAMINA,
	[72959] = FOOD_BUFF_MAX_HEALTH_MAGICKA,
	[72961] = FOOD_BUFF_MAX_MAGICKA_STAMINA,
	[72965] = FOOD_BUFF_REGEN_HEALTH_STAMINA,
	[72968] = FOOD_BUFF_REGEN_HEALTH_MAGICKA,
	[72971] = FOOD_BUFF_REGEN_MAGICKA_STAMINA,
	-- clockwork
	[100498] = FOOD_BUFF_REGEN_HEALTH_REGEN_MAGICKA_MAX_HEALTH_MAX_MAGICKA,
	[100488] = FOOD_BUFF_MAX_ALL,
	[100502] = FOOD_BUFF_REGEN_HEALTH_MAGICKA,
	-- summerset	
	[107789] = FOOD_BUFF_REGEN_HEALTH_REGEN_MAGICKA_MAX_HEALTH_MAX_MAGICKA,
	[107748] = FOOD_BUFF_MAX_HEALTH_MAGICKA_FISHING,
	-- garbage crown crate foods
	[92474] = FOOD_BUFF_MAX_HEALTH_STAMINA,
	[92435] = FOOD_BUFF_MAX_HEALTH_MAGICKA,
	[92476] = FOOD_BUFF_REGEN_HEALTH_STAMINA,
	[92433] = FOOD_BUFF_REGEN_HEALTH_MAGICKA,
	-- more witches festival
	[127531] = FOOD_BUFF_REGEN_HEALTH_MAX_HEALTH_MAX_MAGICKA, 	
	[127572] = FOOD_BUFF_MAX_HEALTH_STAMINA,
	[127596] = FOOD_BUFF_MAX_ALL,
}
